---
Parameters:
  paramHTTPSListener:
    Type: String
    Description: HTTPS Listener ARN
  paramHTTPListener:
    Type: String
    Description: HTTP Listener ARN
  paramTargetGroup:
    Type: String
    Description: Target Group ARN

Resources:
  RuleHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Priority: 20
      ListenerArn: !Ref paramHTTPListener
      Conditions:
      - 
        Field: "host-header"
        Values: 
        - "test1.blog.avrcr.com"
      Actions:
      - 
        Order: 1
        RedirectConfig: 
            Protocol: "HTTPS"
            Port: "443"
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
        Type: "redirect"

  RuleHTTPSListener:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
        Priority: 20
        ListenerArn: !Ref paramHTTPSListener
        Conditions: 
          - 
            Field: "host-header"
            Values: 
              - "test1.blog.avrcr.com"
        Actions: 
          - 
            Type: "forward"
            TargetGroupArn: !Ref paramTargetGroup
            Order: 1
            ForwardConfig: 
                TargetGroups: 
                  - 
                    TargetGroupArn: !Ref paramTargetGroup
                    Weight: 1
                TargetGroupStickinessConfig: 
                    Enabled: false